[workspace]
authors = ["Aathreya Kadambi <aathreyakadambi@berkeley.edu>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "stable-diffusion-x-max"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">25.7"
max = "*"
python = "3.10.*"
numpy = "*"
transformers = ">=4.53.0,<5"
safetensors = "*"
pillow = "*"
matplotlib = "*"
diffusers = ">=0.34.0,<0.35"
pytorch = ">=2.6"